version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 311141532026.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t react-app .
      - docker tag react-app:latest 311141532026.dkr.ecr.us-east-1.amazonaws.com/react-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 311141532026.dkr.ecr.us-east-1.amazonaws.com/react-app:latest
      - echo Updating ECS Service...
      - aws ecs update-service --cluster react-cluster --service react-app-service --force-new-deployment --region us-east-1
      - echo '[{"name":"react-app","imageUri":"311141532026.dkr.ecr.us-east-1.amazonaws.com/react-app:latest"}]' > imagedefinitions.json
  
artifacts:
  files:
    - imagedefinitions.json    
